services:
  ember_widget_demo:
    container_name: ember-widget-demo-${ENVIRONMENT}
    restart: always
    build:
      context: ../..
      args:
        USE_PUBLISHED_PACKAGES: ${USE_PUBLISHED_PACKAGES}
        VITE_EMBER_API_KEY: ${VITE_EMBER_API_KEY}
      dockerfile: apps/demo/Dockerfile
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - shared_network

networks:
  shared_network:
    name: ember-main-${ENVIRONMENT}
    external: true
