services:
  ember_widget_demo:
    container_name: ember-widget-demo-${ENVIRONMENT}
    restart: always
    build: .
    secrets:
      - ember_api_key
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - shared_network

secrets:
  ember_api_key:
    environment: "VITE_EMBER_API_KEY"

networks:
  shared_network:
    name: ember-main-${ENVIRONMENT}
    external: true
